# This playbook takes care of the base things,
# like bash, vim, and git
---
- name: Base setup
  hosts: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Please enter sudo password for command escalation"
      private: yes
  roles:
    - dotfiles
    - ohmyzsh
    - vim
    - git
    - composer
    - java
