---
- name: Install brew cask tap (brew)
  homebrew_tap: name="caskroom/cask" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - tools
    - applications
    - java

- name: Install brew cask tap versions (brew)
  homebrew_tap: name="caskroom/versions" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - tools
    - applications
    - java

- name: Install useful command line desktop tools (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - tools

- name: Install python tools
  pip: name={{ item }} state=present
  with_items: "{{ desktop.pythonTools }}"
  tags:
    - tools
    - python

- name: Install useful desktop applications (brew cask)
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ desktop.applications }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - applications

- name: Ensure MAS is installed
  homebrew: name=mas state=present
  tags:
    - appstore
    - applications

- name: Get MAS account status
  shell: 'mas account'
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  changed_when: false
  tags:
    - appstore
    - applications

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false
  tags:
    - appstore
    - applications

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ desktop.appstore }}"
  when: (item.id|default(item)|string) not in mas_list.stdout
  tags:
    - appstore
    - applications

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: desktop.mas_upgrade_all_apps
  tags:
    - appstore
    - applications

- name: Install user image from Gravatar
  get_url: url=https://s.gravatar.com/avatar/014ba7beb013a1d560e5fd5eaaca3775?s=100 dest=~/.face
  tags:
    - usersettings
