---
- name: Install latest java using homebrew
  homebrew: name="java" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - java

- name: Register openjdk java with System java versions (escalated)
  shell: ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
  become: yes
  tags:
    - java

- name: Install OpenJDK 8 using homebrew
  homebrew: name="openjdk@8" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - java

- name: Register openjdk@8 java with System java versions (escalated)
  shell: ln -sfn /usr/local/opt/openjdk@8/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-8.jdk
  become: yes
  tags:
    - java

- name: Install jenv, gradle, maven and groovy (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ java.dependencies }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - java

- name: Enable required jenv plugins
  shell: eval "$(jenv init -)" && eval "$(jenv enable-plugin {{ item }})"
  with_items: "{{ jenv.plugins }}"
  tags:
    - java

- name: Finding all installed java versions
  find:
    paths:
      - "/Library/Java/JavaVirtualMachines"
    recurse: "no"
    file_type: "any"
  register: installed_java_dirs
  tags:
    - java

- name: Register all java versions with jenv
  command: "jenv add {{ item.path }}/Contents/Home/"
  register: jenv_reg_cmd_res
  failed_when: "jenv_reg_cmd_res.rc != 0 and 'not a valid' in jenv_reg_cmd_res.stdout"
  with_items: "{{ installed_java_dirs.files }}"
  tags:
    - java

- name: Rehash jenv after install of java versions
  shell: eval "$(jenv init -)" && jenv rehash
  tags:
    - java

- name: Get latest oracle java version available
  shell: jenv versions | grep -o 'openjdk64-[0-9]\.*[0-9]*\.*[0-9]*\.*[0-9]*' | sort -r -n -t - -k 2 | head -n 1
  register: jenv_latest_oracle_ver
  failed_when: jenv_latest_oracle_ver.stdout == ""
  tags:
    - java

- name: Set latest Java version as global default for user
  shell: eval "$(jenv init -)" && jenv global {{ jenv_latest_oracle_ver.stdout }}
  tags:
    - java
