---
- name: Install vim plugin dependencies (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ vim.dependencies }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - tools
    - vim
    
- name: Ensure .vim/ folder structure exists
  file: path={{ ansible_user_dir}}/{{ item }} state=directory
  with_items: "{{ vim.folders }}"
  tags:
    - vim

- name: Copy vimrc with plugins using vundle
  template: src="vimrc-vundle.j2" dest="{{ ansible_user_dir }}/.vimrc"
  tags:
    - vim

- name: Install vim vundle
  git: repo={{ item.repo }} dest={{ ansible_user_dir }}/.vim/bundle/{{ item.name }}
  with_items: "{{ vim.vundle }}"
  register: vundle_installed
  tags:
    - vim
    - vundle

- name: Run vundle plugin install
  shell: vim +PluginInstall +qall
  register: vim_plugins_installed
  tags:
    - vim-plugins
    - vim-plugins-install
